defaults:
  - coronary_mask_default
_target_: src.conditioning.mask_embedders.TissueMask
channels: [1,2] #Channels to be edited
num_channels: 4 #Number of channels in the image
iterations_dil: 0 #Number of dilations
iterations_ero: 0 #Number of erosions 