defaults:
  - topo_embedding_defaults@interaction
  - _self_

interaction:
  _target_: src.conditioning.topo_embedders.TopologicalInteractionEmbedder
  tensor_embedder:
    _target_: src.conditioning.tensor_embedders.Voxel2VoxelEmbedder
  channels: [1]
  metric_min: 0
  metric_max: 1
  dim: 3
  connectivity: 6
  inclusion: [[2,3],[1,3]]
  exclusion: [[1,2],[0,1]]
  min_thick: 1
  logging:
    dim_tags: ['n','x','y','z']
    attributes:
      metric_name: "interaction3D"
      metric_dim: 3
