defaults:
  - morph_embedding_defaults@centroid
  - _self_

centroid:
  _target_: src.conditioning.morph_embedders.CentroidEmbedder2D
  tensor_embedder:
    _target_: src.conditioning.tensor_embedders.Seq2SeqEmbedder
  channels: [1, 2]
  emb_axis: ${.tensor_embedder.emb_axis}

  logging:
    dim_tags: ['n', 'emb_axis']
    attributes:
      metric_name: "centroid"
      metric_dim: 2